### PR TITLE
Add support for username

### PR DESCRIPTION
**Pull request by gabriele-v**
Includes also https://github.com/andreacioni/KeeLink/pull/4 changes.
Was not able to test it because of missing custom URL in Android app.

Notes:
getpassforsid.php => getcredforsid.php
updatepsw.php => updatecred.php
updatecred.php => POST fields are now "username" and "password" instead of "key"

### CODE REVIEW

**Comment by andreacioni** [comment]
Hi @gabriele-v , thanks for your contributions. Could you please change every PR destination branch to _test_ ? It will be simpler for me to check your changes if you do so.

**Comment by gabriele-v** [comment]
Hi @andreacioni could you rever your latest commit on test in order to be even with master?
Otherwise I need to do a merge first that won't be quick..

Thanks

**Comment by andreacioni** [comment]
Yes, you are rigth I didn't see it, I reset the test branch to be aligned to master.

**Review by andreacioni — CHANGES_REQUESTED** [review]
Waiting for destination branch changing (same as #4 )

**Comment by gabriele-v** [comment]
Replaced by #7

**Pull request closed without merging**
